feedback/urls.py
from django.urls import path
from . import views

app_name = 'feedback'

urlpatterns = [
    path('', views.home, name='home'),
    path('post', views.post_feedback, name= 'post'),
]

main/urls.py
from django.urls import path, include

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('confirm', views.confirm, name='confirm'),
    path('cases', views.cases, name='cases'),
    path('about-us', views.aboutus, name='about-us'),
    path('donations', views.donate_list, name='donasi'),
    path('contact-us', views.contactus, name='contact-us'),
]

tkppw/urls.py
from django.contrib import admin
from django.urls import include, path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('report/', include('report.urls')),
    path('services/', include('services.urls')),
    path('donation/', include('donation.urls')),
    path('feedback/', include('feedback.urls')),
    path('about-us/', views.aboutus),
    path('cases/', views.cases),
    path('donations/', views.donate_list),
    path('', include('perloginan.urls')), 
]

feedback/models.py
from django.db import models

# Create your models here.
class Feedback(models.Model):
    name = models.CharField(max_length=50)
    email =  models.CharField(max_length=30)
    message = models.CharField(max_length=500)

feedback/forms.py
from django import forms
from django.forms import Textarea, TextInput

class feedbackform(forms.Form):
    error_messages = {
        'required': 'This field is required.'
    }
    attrs = {
        'class' : 'form-control'
    }
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label='Nama ', max_length=50, required=True)
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label = 'Email ', max_length=30, required=True)
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}), label = 'Message ',max_length=500, required=True)

feedback/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from feedback.models import Feedback
from feedback.forms import feedbackform

# Create your views here.
def home(request):
    form_feedback = feedbackform()
    data = Feedback.objects.all()
    response = {'form_feedback' : form_feedback, 'data' : data}
    return render(request, 'feedback.html', response)



def post_feedback(request):
    if request.method == 'POST':
        form = feedbackform(request.POST or None)
        response_data = {}
        if form.is_valid():
            response_data['name'] = request.POST['name']
            response_data['email'] = request.POST['email']
            response_data['message'] = request.POST['message']

            data_feedback = Feedback(name=response_data['name'],
                                   email=response_data['email'],
                                   message=response_data['message'],
                                   )
            data_feedback.save()
            return redirect('main:confirm')

feedback/templates/feedback.html
{% extends 'base.html' %}   
{% load static %}

{% block meta %}

{% endblock meta %}

{% block content %} 

<div style="text-align: center;
padding: 1%;padding-bottom: 3%;"><h1>Feedback</h1><br>
<h5>Tolong tuliskan saran atau keluhan mengenai servis yang kami berikan apa bila ada.</h5></div>
<div style="margin: auto;
border: 2px solid black;
border-radius: 10px;
width: 75%;
padding: 20px">

<form method= "POST" action="{% url 'feedback:post' %}">
    {% csrf_token %}
        {{ form_feedback.as_p }}
 
    <div>
        <a href="{% url 'main:home' %}" style="text-decoration: none; color: black;"><button class="button cancel-button">Cancel</a>
        <button class="button submit-button">Submit</a>
    </div>
</form>
</div>

<div style= "margin: auto;
border: 2px solid #2f2f2f;
background-color: #2f2f2f;
border-radius: 10px;
width: 75%;
margin-top: 10px;
padding: 20px">
    {%for i in data %}
    <div style= "margin: auto;
    border: 2px solid #2f2f2f;
    background-color: white;
    border-radius: 10px;
    width: 97%;
    margin-top: 10px;
    padding: 10px;
    line-height: 1,5;">
   
        <h5><b>{{i.name}}</b>  |  {{i.email}} </h5>
        <h6>{{i.message}}</h6>
    </div>
    {% endfor %}
</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
{% endblock content %}