main/urls.py
from django.urls import path, include

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('confirm', views.confirm, name='confirm'),
    path('cases', views.cases, name='cases'),
    path('about-us', views.aboutus, name='about-us'),
    path('donations', views.donate_list, name='donasi'),
    path('contact-us', views.contactus, name='contact-us'),
]

services/urls.py
from django.urls import path
from . import views

app_name = 'services'

urlpatterns = [
    path('', views.home, name='home'),
    path('post', views.post_service, name= 'post'),
]

tkppw/urls.py
from django.contrib import admin
from django.urls import include, path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('report/', include('report.urls')),
    path('services/', include('services.urls')),
    path('donation/', include('donation.urls')),
    path('feedback/', include('feedback.urls')),
    path('about-us/', views.aboutus),
    path('cases/', views.cases),
    path('donations/', views.donate_list),
    path('', include('perloginan.urls')), 
]

services/models.py
from django.db import models

# Create your models here.
class Service(models.Model):
    name = models.CharField(max_length=160)
    address = models.CharField(max_length=200)
    phone = models.IntegerField(max_length=15)
    detail = models.CharField(max_length=500, default='')

services/forms.py
from django import forms
from django.forms import ModelForm,  Textarea, TextInput

class serviceforms(forms.Form):
    error_messages = {
        'required': 'This field is required.'
    }
    attrs = {
        'class' : 'form-control'
    }
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label='Nama', max_length=160, required=True)
    address = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}), label = 'Alamat', max_length=200, required=True)
    phone = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label = 'Telepon',max_length=15, required=True)
    detail = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}), label = 'Detail', max_length=500, required=True)

services/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from services.models import Service
from services.forms import serviceforms

# Create your views here.
def home(request):
    form_service = serviceforms()
    data = Service.objects.all()
    response = {'form_service' : form_service, 'data' : data}
    return render(request, 'services.html', response)

def post_service(request):
    if request.method == 'POST':
        form = serviceforms(request.POST or None)
        response_data = {}
        if form.is_valid():
            response_data['name'] = request.POST['name']
            response_data['address'] = request.POST['address']
            response_data['phone'] = request.POST['phone']
            response_data['detail'] = request.POST['detail']

            data_service = Service(name=response_data['name'],
                                   address=response_data['address'],
                                   phone=response_data['phone'],
                                   detail=response_data['detail'],
                                   )
            data_service.save()
            return redirect('main:confirm')

services/templates/services.html
{% extends 'base.html' %}   
{% load static %}

{% block meta %}

{% endblock meta %}

{% block content %} 

<div style="text-align: center;
padding: 1%;padding-bottom: 3%;"><h1>Services</h1><br>
<h5>Tolong tuliskan pada halaman ini informasi yang dibutuhkan untuk meminta service dari kami agar kami dapat menentukan
    tipe service yang bisa kami berikan. <br><br>Kemudian tunggulah balasan dari kami kepada email yang diberikan.
</h5></div>
<div style="margin: auto;
border: 2px solid black;
border-radius: 10px;
width: 75%;
padding: 20px;
">

<form method= "POST" action="{% url 'services:post' %}">
    {% csrf_token %}
    {{ form_service.as_p }}
    <div>
        <a href="{% url 'main:home' %}" style="text-decoration: none; color: black;"><button class="button cancel-button">Cancel</a>
        <button class="button submit-button">Submit</a>
    </div>
    <h3 style="text-align: center;float: none; margin-top: 5%; margin-bottom: 2%;">Antrian</h3>
    {%for i in data %}
        <div style="margin: auto;
        border: 2px solid black;
        border-radius: 10px;
        width: 75%;
        margin-top: 10px;
        padding: 20px;">
            <h4>{{i.name}}</h4>
            <p>{{i.detail}}<p>
        </div>
        <br>
    {% endfor %}
    
</form>

</div>
{% endblock content %}