main/urls.py
from django.urls import path, include

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('confirm', views.confirm, name='confirm'),
    path('cases', views.cases, name='cases'),
    path('about-us', views.aboutus, name='about-us'),
    path('donations', views.donate_list, name='donasi'),
    path('contact-us', views.contactus, name='contact-us'),
]

perloginan/urls.py
from django.urls import path
from perloginan.views import logIn, signUp, logOut


app_name = 'perloginan'

urlpatterns = [
    path('login/', logIn, name='login'),
    path('signup/', signUp, name='signup'),
    path('logout/', logOut, name='logout'),
]

tkppw/urls.py
from django.contrib import admin
from django.urls import include, path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('report/', include('report.urls')),
    path('services/', include('services.urls')),
    path('donation/', include('donation.urls')),
    path('feedback/', include('feedback.urls')),
    path('about-us/', views.aboutus),
    path('cases/', views.cases),
    path('donations/', views.donate_list),
    path('', include('perloginan.urls')), 
]

perloginan/models.py
from django.db import models

# Create your models here.

perloginan/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'id' : 'signIn-username',
        'placeholder' : 'Username',
        'type' : 'text',
        'style' : 'width: 20vw;',
        'required' : True
    }))

    password = forms.CharField(label="Password", widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'id' : 'signIn-password',
        'placeholder' : 'Password',
        'type' : 'password',
        'style' : 'width: 20vw;',
        'required' : True
    }))

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(label="First name", widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'id' : 'signUp-firstName',
        'placeholder' : 'First name',
        'type' : 'text',
        'style' : 'width: 30vw;',
        'required' : True
    }))

    last_name = forms.CharField(label="Last name", widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Last name',
        'id' : 'signUp-lastName',
        'type' : 'text',
        'style' : 'width: 30vw;',
        'required' : True
    }))

    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'id' : 'signUp-username',
        'placeholder' : 'Username',
        'type' : 'text',
        'style' : 'width: 30vw;',
        'required' : True
    }))

    password1 = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={
        'class' : 'form-control',
        'id' : 'signUp-password1',
        'placeholder' : 'Password',
        'type' : 'password',
        'style' : 'width: 30vw;',
        'required' : True
    }))
    password2 = forms.CharField(label="Confirm password", widget=forms.PasswordInput(attrs={
        'class' : 'form-control',
        'id' : 'signUp-password2',
        'placeholder' : 'Confirm Password',
        'type' : 'password',
        'style' : 'width: 30vw;',
        'required' : True
    }))

class Meta:
    model = User
    fields = ['first_name', 'last_name', 'username', 'password1', 'password2']

perloginan/views.py
from django.shortcuts import render, redirect
from perloginan.forms import LoginForm, SignUpForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


# Create your views here.
def logIn(request):
    if request.method == "POST":
        form = LoginForm(data = request.POST)

        if form.is_valid():
            usernameInput = request.POST["username"]
            passwordInput = request.POST["password"]

            print(usernameInput, passwordInput)
            user = authenticate(request, username = usernameInput, password = passwordInput)

            if user is not None:
                login(request, user)
                return redirect('login')

        else:
            messages.error(request, 'Invalid entry')

    else:
        form = LoginForm()

    context = {
        "form" : form,
    }

    return render(request, "login.html", context)

def signUp(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("login")

        else:
            for msg in form.error_messages:
                messages.error(request, 'Invalid entry')

    else:
        form = SignUpForm()

    context = {
        'form' : form
    }

    return render(request, "signup.html", context)

def logOut(request):
    logout(request)
    return redirect("login")

perloginan/templates/login.html
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'css/style_login.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

{% block content %} 


<div class="card" style="width: 75%; border-radius: 10px; margin: 10%; " id="center">
    <div class="card-body">

        <div class="title" id="center" style="text-align: center;">
            <h3 style="text-align: center;">Masuk</h3>
        </div>
        <div style="padding: 10%;" id="center">
            <div class="main d-flex flex-column justify-content-center" id="center">
                <div class="row">
        
            
                    <div class="right-page col >
                       
                        {% if user.is_authenticated == False %}
                        <div class="login content mx-5 my-5">
                            {% if messages %}
                                {% for message in messages %}
                                    <p>{{message}}</p>
                                {% endfor %}
                            {% endif %}
                            
                            <div class="login-form" style="margin: 10%;">
                                <form method="POST">
                                    {% csrf_token %} 
                                    {{ form }}
                                    <div style="margin-top: 5%;">
                                        <button type="submit" name="btn-login" id="btn-logIn" class="btn btn-dark mt-4">LOGIN</button>
                                    </div>
                                </form>
                            </div>
            
                            <div class="info mt-5">
                                <p>
                                    Don't have an account? <a id="nya" href="{% url 'perloginan:signup' %}"><strong style="color:black;">Sign up.</strong></a>
                                </p>
                            </div>
                        </div>
            
                        {% else %}
                            <div class="success mt-5 ml-5">
                                <div class="greeting mt-5">
                                    <h3>Welcome,</h3>
                                    <h1 style="font-weight: 700px;"><span class="highlight">{{user.username}}.</span></h1>
                                </div>
                                <div class="btn-logout" style="display: block; width:60px ;border-radius: 10px;margin-bottom: 10%; margin-left: auto; text-align: center;
                                margin-right: auto;">
                                    <form action="{% url 'logout' %}">
                                        <input type="submit" id="btn-logOut" class="btn btn-dark" value="Log out">
                                    </form>
                                </div>
                            </div>

                            
                        {% endif %}
                    </div>
                </div>
            
            
            </div>
            
        </div>
    </div>
  </div>




  <div class="back-button">
    <a style="display: block; width:60px ;border-radius: 10px;margin-bottom: 10%; margin-left: auto; text-align: center;
    margin-right: auto;" id= "bu" class="btn btn-warning" href="/" role="button">Back</a>
</div>

{% endblock content %}

perloginan/templates/signup.html
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'css/style_login.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

{% block content %}

<div class="card" style="width: 75%; border-radius: 10px; margin: 10%;" id="center">
    <div class="card-body">

        <div class="title" id="center" style="text-align: center;">
            <h3 style="text-align: center;">Sign Up</h3>
        </div>
        <div style="margin: 5%;">
            <div class="row">

            </div>

            <div class="right-page col">
                <div class="login-content mx-5 my-5">



                    <div class="register-form" style="margin: 10%;">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form }}
                            <div style="margin-top: 5%;">
                                <button type="submit" name="btn-signup" id='btn-signUp' class="btn btn-dark mt-4">SIGN
                                    UP</button>
                            </div>
                        </form>
                    </div>

                    <div class="info mt-5" style="margin-top: 5%;">
                        <p>
                            Have an account already? <a id="nya" href="{% url 'perloginan:login' %}"><strong
                                    style="color:black;">Sign in.</strong></a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

    </div>


</div>
</div>

<div class="back-button">
    <a style="display: block; width:60px ;border-radius: 10px;margin-bottom: 10%; margin-left: auto; text-align: center;
        margin-right: auto;" id="bu" class="btn btn-warning" href="/" role="button">Back</a>
</div>






















{% endblock content %}