donation/urls.py
from django.urls import path
from . import views

app_name = 'donation'

urlpatterns = [
    path('', views.home, name='home'),
    path('post', views.post_donation, name= 'post'),
]

feedback/urls.py
from django.urls import path
from . import views

app_name = 'feedback'

urlpatterns = [
    path('', views.home, name='home'),
    path('post', views.post_feedback, name= 'post'),
]

main/urls.py
from django.urls import path, include

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('confirm', views.confirm, name='confirm'),
    path('cases', views.cases, name='cases'),
    path('about-us', views.aboutus, name='about-us'),
    path('donations', views.donate_list, name='donasi'),
    path('contact-us', views.contactus, name='contact-us'),
]

report/urls.py
from django.urls import path
from . import views

app_name = 'report'

urlpatterns = [
    path('', views.home, name='home'),
    path('post', views.post_report, name= 'post'),
]

services/urls.py
from django.urls import path
from . import views

app_name = 'services'

urlpatterns = [
    path('', views.home, name='home'),
    path('post', views.post_service, name= 'post'),
]

tkppw/urls.py
from django.contrib import admin
from django.urls import include, path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('report/', include('report.urls')),
    path('services/', include('services.urls')),
    path('donation/', include('donation.urls')),
    path('feedback/', include('feedback.urls')),
    path('about-us/', views.aboutus),
    path('cases/', views.cases),
    path('donations/', views.donate_list),
    path('', include('perloginan.urls')), 
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
  <style>
    * {box-sizing: border-box;}
    body {font-family: Verdana, sans-serif;}
    .mySlides {display: none;}
    img {vertical-align: middle;}
    
    /* Slideshow container */
    .slideshow-container {
      max-width: 100%;
      max-height: 10%;
      min-height: 10%;
      position: relative;
      margin: auto;
      
    }
    
    /* Caption text */
    .text {
      color: #f2f2f2;
      font-size: 15px;
      padding: 8px 12px;
      position: absolute;
      bottom: 8px;
      width: 100%;
      text-align: center;
    }
    
    /* Number text (1/3 etc) */
    .numbertext {
      color: #f2f2f2;
      font-size: 12px;
      padding: 8px 12px;
      position: absolute;
      top: 0;
    }
    
    /* The dots/bullets/indicators */
    .dot {
      height: 15px;
      width: 15px;
      margin: 0 2px;
      background-color: #bbb;
      border-radius: 50%;
      display: inline-block;
      transition: background-color 0.6s ease;
    }
    
    .active {
      background-color: #717171;
    }
    
    /* Fading animation */
    .fade {
      -webkit-animation-name: fade;
      -webkit-animation-duration: 2s;
      animation-name: fade;
      animation-duration: 2s;
    }
    
    @-webkit-keyframes fade {
      from {opacity: .4} 
      to {opacity: 1}
    }
    
    @keyframes fade {
      from {opacity: .4} 
      to {opacity: 1}
    }
    
    /* On smaller screens, decrease text size */
    @media only screen and (max-width: 300px) {
      .text {font-size: 11px}
    }
    </style>
</head>

<body> 
  <header>
      <div class="navbar">
          <ul>
              <li style="display: block;
              color: rgb(255, 152, 152);
              font-size: 18px;
              text-align: center;
              padding: 14px 15px;
              text-decoration: none;
              float: left;
              background-color: rgb(75, 75, 75);
              border-radius: 50px;
              width: 100px;
              border-style: inset;">Co<span style="color: rgb(255, 255, 255);">Feed</span></li>
              <li><a href="{% url 'main:home' %}" class="home">Home</a></li>
              <li><a href="{% url 'main:about-us' %}" class="about-us">About Us</a></li>
              <li><a href="{% url 'main:cases' %}" class="cases">Cases</a></li>
              <li><a href="{% url 'services:home' %}" class="services">Services</a></li>
              <li><a href="{% url 'report:home' %}" class="report-case">Report Case</a></li>
              <li>
                <div class="dondrop">
                  <a class="dropbutton">Donation</a>
                  <div class="dropdown-content">
                    <a href="{% url 'donation:home' %}" class="donation">Make Donation</a>
                    <a href="{% url 'main:donasi' %}" class="donasi">Donations</a>
                  </div>
                </div>
              </li>
              <li><a href="{% url 'feedback:home' %}" class="feedback">Feedback</a></li>
              
          </ul>
      </div>
  </header>
  <div class="slideshow-container">

    <div class="mySlides fade">
      <div class="numbertext">1 / 4</div>
      <img src="{% static 'css/image.jpg' %}" style="width:100%">
      <div class="text">COVID-19</div>
    </div>
    
    <div class="mySlides fade">
      <div class="numbertext">2 / 4</div>
      <img src="{% static 'css/po.jpg' %}" style="width:100%">
      <div class="text">COVID-19</div>
    </div>
    
    <div class="mySlides fade">
      <div class="numbertext">3 / 4</div>
      <img src="{% static 'css/forest_glade_autumn-wallpaper-1920x600.jpg' %}" style="width:100%">
      <div class="text">COVID-19</div>
    </div>
    
    <div class="mySlides fade">
      <div class="numbertext">4 / 4</div>
      <img src="{% static 'css/foto.jpg' %}" style="width:100%">
      <div class="text">OUR TEAM</div>
    </div>
    </div>
    <br>
    
    <div style="text-align:center">
      <span class="dot"></span> 
      <span class="dot"></span> 
      <span class="dot"></span> 
      <span class="dot"></span> 
    </div>
    
    <script>
    var slideIndex = 0;
    showSlides();
    
    function showSlides() {
      var i;
      var slides = document.getElementsByClassName("mySlides");
      var dots = document.getElementsByClassName("dot");
      for (i = 0; i < slides.length; i++) {
        slides[i].style.display = "none";  
      }
      slideIndex++;
      if (slideIndex > slides.length) {slideIndex = 1}    
      for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active", "");
      }
      slides[slideIndex-1].style.display = "block";  
      dots[slideIndex-1].className += " active";
      setTimeout(showSlides, 2000); // Change image every 2 seconds
    }
    </script>
  {% block content %}
  {% endblock content %}
  <footer>
      <div class="bapak-container">
          <div class="container" style="padding: 2%; padding-top: 5%;">
              <div class="row">
                  <div class="col">
                      <p style="line-height: 180%;"><i class="fas fa-phone-square-alt" style="font-size: 30px;"></i>+62812 6399 2001</p>
                  </div>
                  <div class="col">
                      <p style="line-height: 180%;"><i class="far fa-envelope" style="font-size: 30px;"></i>cofeed@cs.ui.ac.id</p>
                  </div>
                  <div class="col">
                      <p style="line-height: 180%;"><i class="fas fa-map-marker-alt" style="font-size: 30px; text-align: justify; "></i> Pondok Cina,Kecamatan Beji,Depok, Jawa Barat
                      </p>
                  </div>
                  <div class="col">
                    <br><br>
                    <a href="{% url 'main:contact-us' %}" class="btn btn-primary btn-lg" style="text-align: center; border-radius: 30px;">Contact Us</a>
                  </p>
                </div>
              </div>
      
          </div>
          <br>
          <div class="anak-container2" style="margin-top: -10%">
              <div class="col-sm-3">
                  <h3 style="text-align:center;color:#CAA3A4;">CoFeed</h3>
                      <p style="text-align: justify;">CoFeed adalah projek
                          untuk memenuhi tugas 
                          mata kuliah perancangan 
                          dan pemrograman web 
                          fasilkom UI. Web dipergunakan untuk 
                          mengatasi penyebaran covid-19.</p>
         
              </div>
     
          <div class="col-sm-3">
            <h3 style="text-align:center; color:#CAA3A4;">Useful Links</h3>
            <div style="text-align:center;">
              <a href="{% url 'main:about-us' %}" class="about-us" style="color: #CAA3A4; text-align:center;text-decoration: none; ">About Us</a> <br>
              <a href="{% url 'services:home' %}" class="services" style="color: #CAA3A4; text-align:center;text-decoration: none;">Services</a> <br>
              <a href="{% url 'report:home' %}" class="report-case" style="color: #CAA3A4 ;text-decoration: none;">Report Case</a> <br>
              <a href="{% url 'main:home' %}" class="cases" style="color: #CAA3A4; text-decoration: none;">Cases</a>
            </div>
          </div>
          <div class="col-sm-3">
              <h3 style="color: #CAA3A4; text-align:center;">Recent News</h3>
              <p style="text-align: justify;"><b>Bertambah 3.602, Total Kasus Corona di RI</b>
                <br>Kasus positif virus Corona COVID-19) di RI hari ini kembali bertambah.
                Sebanyak 3.602 kasus baru Corona ditemukan hari ini di Indonesia.</p>
      
          </div>
          <div>
               </div>
      </div>
  </div>
  <p style="background-color: black;color: white; font-size: 15px; padding: 5px ;">Copyright 2020-2021. All rights reserved - Designed by Kelompok C11</p>
  </div>
  </footer>
</body>

</html>